# Slacker node runner configuration

# port: expose port for slacker node runner.
# specs.rootFolder: the full folder path of your slacker test project.
# specs.specFolder: the root level spec folder path. Typically it is under 'spec' folder.
port: 8000
specs:
  rootFolder: /opt/slacker-test
  specFolder: /opt/slacker-test/spec
